## konlpy

In [1]:
from konlpy.tag import Okt
# streamlit error 
# sol) update tweepy to 3.10.0

In [2]:
okt = Okt()

# systemerror ( already loaded in another classloader
# sol) In env\konlpy\jvm.py, every * to be deleted from folder_suffix
# https://byeon-sg.tistory.com/entry/자연어-처리-konlpy-설치-오류-okt에러-already-loaded-in-another-classloader-SystemErro-1 [wave])

In [3]:
# Pos-tagging(형태소 분석)
text = '나는 코딩을 무지무지 좋아합니다!'
okt.pos(text)

[('나', 'Noun'),
 ('는', 'Josa'),
 ('코딩', 'Noun'),
 ('을', 'Josa'),
 ('무지무지', 'Adverb'),
 ('좋아합니다', 'Adjective'),
 ('!', 'Punctuation')]

In [89]:
# Pos-tagging(형태소 분석)
text = '나는 코딩을 무지무지 좋아합니다!'

#pos와는 다르게 단순 나누기만함
okt.morphs(text)

['나', '는', '코딩', '을', '무지무지', '좋아합니다', '!']

In [90]:
# Extracting Nouns

text = '아이폰이랑 갤럭시중 어느 게 더 좋은 핸드폰이야??'
okt.nouns(text)

# 간혹 명사 이외의 것(게, 더)가 명사로 인식된다

['아이폰', '갤럭시', '게', '더', '핸드폰']

In [91]:
# 정규화 : 어지럽힌 문장을 깔끔하게 처리
text = '안녕하세욬ㅋㅋㅋ 반가워요 샤릉해'
print(okt.normalize(text))


안녕하세요ㅋㅋㅋ 반가워요 사랑해


## BOW 실습

In [125]:
# bag of words
# 간단하게 영어 단어 제거 => 정규화 및 필요 없는 단어, 특수문자 제거 => bow

from konlpy.tag import Okt
import re
import pandas as pd

okt = Okt()
df = pd.read_excel('results.xlsx')
df.info()
df = df.fillna(' ')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   comment    47 non-null     object
 1   author     47 non-null     object
 2   date       47 non-null     object
 3   num_likes  47 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 1.6+ KB


In [126]:
# 1. 필요 없는(이모티콘 등 의미 없는) 부분 전처리
# 2. youtube comments에 @nickname~ 이런 경우가 있어, author column의 문자열들 모두 comments에서 모두 삭제해야 한다.

# https://stackoverflow.com/questions/10968558/python-re-sub-with-a-list-of-words-to-find


# 해결 : authors_regex에서 사전으로 특수문자 제거(메타 char 될 수 있는거) 제거 후, authors_regex부터 제거

author = set()
authors = set(['@' + re.sub('\W+', '', i) for i in df['author']])
authors_regex = "|".join(authors)

for line in df['comment']:
    line = re.sub('\W+',' ', line)           # 특수 문자 스페이스로 대체.
    line = re.sub(authors_regex, ' ', line)     # 특별한 의미 없는 단어 스페이스로 대체.

comments = []
for line in df['comment']:

        line = re.sub(authors_regex, ' ', line)  # 댓글 중 tag한 거 다 제거
        line = re.sub('\W+',' ', line)           # 특수 문자 스페이스로 대체.
        line = re.sub('\d+',' ', line)         # 수치 스페이스로 대체.
        line = re.sub('\n',' ',line)             # line return 스페이스로 대체.
        line = re.sub('[\[\]]', ' ',line)        # 대괄호 스페이스로 대체.
        line = re.sub('[a-zA-Z]',' ',line)       # 영문 스페이스로 대체.
        line = re.sub('[ㄱ-ㅎ | ㅏ-ㅣ]', ' ', line)     # 단모음, 단자음 스페이스로 대체.
        line = re.sub('\s+', ' ', line)          # 잉여 스페이즈 줄임.
        # line = okt.normalize(line)            # 시간이 너무 걸림. 그리고 불필요한 작업
        comments.append(line.strip())


In [127]:
print(authors_regex[:10])
print(comments[:10])

@jushan|@윤
['진짜 기여워잉', '망고처럼 꽃돌이가 너무 귀엽네옇', '귀여운 새침이', '꽃돌이 남자에요 여자에오', '꽃돌이는 여자에요', '아 너무 귀여워', '제가 키웠던 토끼가 자기 집 위에 올라가서 못 내려오던 이유가 있었군요', '이쁜것 아휴 꽃돌이 관절 소즁해', '이꽃돌씨와 우리 깜토 까미토끼 가만나면 어덯게 될까요 큰토끼님 답글 부탁드려용', '꽃돌이는배고파 헉 감사해요 나중에 한번 될수있으면 꽃돌이보러갈께요']


In [128]:
# COMMENT에서 명사, 형용사, 동사만 추출
com_noun = {}
com_verb = {}
com_adj = {}



for com in comments:
    tmp = okt.pos(com)

    # 품사 태그를 통해 명, 형, 동 구분
    for t in tmp:
        word, tag = t[0], t[1]
        if tag == 'Noun':
            if word in com_noun:
                com_noun[word] += 1
            else:
                com_noun[word] = 1

        elif tag == 'Verb':
            if word in com_verb:
                com_verb[word] += 1
            else:
                com_verb[word] = 1

        elif tag == 'Adjective':
            if word in com_adj:
                com_adj[word] += 1
            else:
                com_adj[word] = 1

com_noun = sorted(list(com_noun.items()), key= lambda x: (x[1], x[0]), reverse=True)
com_verb = sorted(list(com_verb.items()), key= lambda x: (x[1], x[0]), reverse=True)
com_adj = sorted(list(com_adj.items()), key= lambda x: (x[1], x[0]), reverse=True)

In [129]:
print(com_noun[:10])


[('돌이', 18), ('꽃', 17), ('토끼', 10), ('수', 4), ('제', 3), ('이불', 3), ('위', 3), ('앞다리', 3), ('땐', 3), ('꽃돌', 3)]


In [130]:
print(com_verb[:10])

[('큰', 4), ('해서', 2), ('않아', 2), ('만나면', 2), ('흘리는', 1), ('했는데', 1), ('해주면', 1), ('해주는', 1), ('해', 1), ('한다', 1)]


In [120]:
print(com_adj[:10])

[('같은', 175), ('없는', 120), ('입니다', 112), ('있는', 93), ('이런', 86), ('나쁜', 84), ('같은데', 83), ('없다', 79), ('좋은', 73), ('많은', 71)]


## DTM & TFIDF

In [131]:
# dtm class
import numpy as np

class DTM:
    def __init__(self):
        self.vocabulary = None


    def dtm_build(self, comments):
        comments_remake = []
        col_word = set()

        # 형태소 및 단어에서 단어 글자 크기가 1 이하이면 제외(sklearn과 동일하게 작동하도록 함)
        for com in comments:
            comments_remake.append([])
            tmp = com.split()

            for word in tmp:

                word_re = okt.pos(word)
                if len(word_re[0][0]) < 2:
                    continue
                col_word.add(word_re[0][0])
                comments_remake[-1].append(word_re[0][0])
        
        col_word = list(col_word)

        dtm = np.zeros(shape=(len(comments_remake), len(col_word)), dtype=np.int32) # row = comments, col = set of unique voca
        
        for i in range(len(comments_remake)):
            comment = comments_remake[i]
            for j in range(len(comment)):
                word = comment[j]
                if word in col_word:
                    idx = col_word.index(word)
                    dtm[i, idx] += 1


        self.vocabulary = {i:word for i, word in enumerate(col_word)}
        return dtm

            
dtm = DTM()
new_dtm = dtm.dtm_build(comments)
print(new_dtm)
# print(dtm.vocabulary)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [132]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

comments_remake = []
col_word = set()


for com in comments:
    tmp = com.split()
    strs = []
    for word in tmp:
        word_re = okt.pos(word)
        col_word.add(word_re[0][0])
        strs.append(word_re[0][0])
    comments_remake.append(' '.join(strs))
    
tfidfv = TfidfVectorizer().fit(comments_remake)
tfidf_matrix = tfidfv.transform(comments_remake).toarray()
voca_dict = tfidfv.vocabulary_


for i in range(tfidf_matrix.shape[0]):
    max_value = tfidf_matrix[i].argmax()
    m = tfidf_matrix[i].max()
    if  m > 0.7 and m < 1:
        print(list(voca_dict.keys())[list(voca_dict.values()).index(max_value)], m)

진짜 0.7422031318471273
남자 0.7422031318471273
귀여워 0.7856389514504228
관절 0.7071067811865475
나가요 0.7071067811865475
동글동글 0.7071067811865475
너무 0.8060093627548559
아이쿠 0.7422031318471273
귀여워 0.8420957014832894
기여웡 0.8518852253129331
짧은 0.7399133856298227
뭉툭 0.8518852253129331
